# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clovapatra-game
  labels:
    app: clovapatra-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clovapatra-game
  template:
    metadata:
      labels:
        app: clovapatra-game
    spec:
      containers:
        - name: clovapatra-game
          image: clovapatra-container-registry.kr.ncr.ntruss.com/clovapatra-game:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_PORT
              value: "8000"
            - name: REDIS_HOST
              value: "redisc-2vvlm0.vpc-cdb.ntruss.com"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          command: ["node"]
          args: ["dist/main.js"]
      nodeSelector:
        ncloud.com/nks-nodepool: game
      imagePullSecrets:
        - name: regcred

---
# Service

apiVersion: v1
kind: Service
metadata:
  name: clovapatra-game-service
  labels:
    app: clovapatra-game
spec:
  type: ClusterIP
  selector:
    app: clovapatra-game
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
