name: Push to Naver Cloud Source Commit Repo

on:
  push:
    branches:
      - main

jobs:
  push_to_ncp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 히스토리 가져오기

      - name: Set up Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add NCP Remote
        run: |
          git remote add ncp https://${{ secrets.NCP_USERNAME }}:${{ secrets.NCP_PASSWORD_URL_ENCODED }}@${{ secrets.NCP_REPO_URL }}

      - name: Push to NCP Main Branch
        run: |
          git push ncp main --force
